apiVersion: v1

kind: Pod

metadata:
    name: mysql-pod
    labels:
        name: mysql-pod
        app: demo-jhipster
        
spec:
    containers:
        - name: mysql-pod
          image: mysql:8.0.18
          env:
          - name: MYSQL_USER
            value: "root"
          - name: MYSQL_ALLOW_EMPTY_PASSWORD
            value: "yes"
          - name: MYSQL_DATABASE
            value: "payeeservice"
          command: ["mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp"]
          ports:
          - containerPort: 3306