apiVersion: v1

kind: Service

metadata:
    name: payee-kube-service
    labels:
        name: payee-kube-service
        app: demo-jhipster
    
spec:
    type: LoadBalancer
    ports:
        - port: 8081
          targetPort: 8081
    selector:
        name: payee-service-pod
        app: demo-jhipster